version: "3.9"

services:
  devopsdb:
    image: chinmaich316/myrep:db
    ports:
      - "3306:3306"
    

  application:
    image: chinmaich316/myrep:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    

